version: '3'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: nginx 
    ports:
      - '9000:9000'
    depends_on:
      - back-end

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: backend-api # name for the image you're building
    ports:
    - '5252:5252'
